config:
  backup: true
  banner: true
  create: true
  dotpath: .
  keepdot: true
  workdir: ~/Templates
dotfiles:
  nushell:
    src:  nushell
    dst:  ~/.config/nushell
    link: absolute
  helix:
    src:  helix
    dst:  ~/.config/helix
    link: absolute
  spicetify:
    src:  spicetify/config-xpui.ini
    dst:  ~/.config/spicetify/config-xpui.ini
    link: absolute
  betterdiscord:
    src:  BetterDiscord
    dst:  ~/.config/BetterDiscord
    link: absolute
  fishrc:
    src:  fish/config.fish
    dst:  ~/.config/fish/config.fish
    link: absolute
  latte:
    src:  latte
    dst:  ~/.config/latte
    link: absolute
  bashrc:
    src:  bashrc
    dst:  ~/.bashrc
    link: absolute
  zshrc:
    src:  zsh/zshrc
    dst:  ~/.zshrc
    link: absolute
  themes:
    src:  themes
    dst:  ~/.config/themes
    link: absolute
profiles:
  Quetz:
    dotfiles:
    - nushell
    - helix
    - spicetify
    - betterdiscord
    - fishrc
    - latte
    - bashrc
    - zshrc
    - themes
  garrr:
    dotfiles:
    - nushell
    - helix
    - spicetify
    - betterdiscord
    - fishrc
    - latte
    - bashrc
    - zshrc
    - themes
