config:
  backup: true
  banner: true
  create: true
  dotpath: .
  keepdot: true
  workdir: ~/Templates
dotfiles:
  nushell:
    src: .config/nushell
    dst: ~/.config/nushell
    link: absolute
  helix:
    src: .config/helix
    dst: ~/.config/helix
    link: absolute
  spicetify:
    src: .config/spicetify/config-xpui.ini
    dst: ~/.config/spicetify/config-xpui.ini
    link: absolute
  betterdiscord:
    src: .config/BetterDiscord
    dst: ~/.config/BetterDiscord
    link: absolute
  fishrc:
    src: .config/fish/config.fish
    dst: ~/.config/fish/config.fish
    link: absolute
  latte:
    src: .config/latte
    dst: ~/.config/latte
    link: absolute
  bashrc:
    src: .bashrc
    dst: ~/.bashrc
    link: absolute
  zshrc:
    src: .zshrc
    dst: ~/.zshrc
    link: absolute
profiles:
  Quetz:
    dotfiles:
    - nushell
    - helix
    - spicetify
    - betterdiscord
    - fishrc
    - latte
    - bashrc
    - zshrc
