# Path to your oh-my-zsh installation.
export ZSH="$HOME/Templates/zsh/oh-my-zsh"

CASE_SENSITIVE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

plugins=(
	command-not-found
	git
	nvm
	sudo
	yarn
	zoxide
	zsh-autosuggestions
	zsh-syntax-highlighting
	)

source $ZSH/oh-my-zsh.sh

#My stuff

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#F35645"

source <(carapace _carapace zsh)

alias x='exit'
alias c='clear'
alias p='paru'
alias r='source ~/.zshrc'
# alias w ='cd ~/Documents/Projects'
# alias sd ='cd ~/Documents/Projects/siarune.dev'

export PATH=/home/.local/bin:$PATH
source ~/.nvm/nvm.sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

 eval "$(oh-my-posh init zsh --config ~/.config/themes/sia.omp.json)"
# eval "$(starship init zsh)"

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true

# pnpm
export PNPM_HOME="/home/sia/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end